### ISSUE TITLE
Duplicate fields names

### ISSUE THREAD

**Issue by dmpotapenko** [alexsasharegan/vue-breakpoint#1]
During component inizialization the next  error occurs:
![image](https://user-images.githubusercontent.com/10564242/49947079-60453a80-ff01-11e8-8277-cd39763ca767.png)

Pls, check **BreakpointComponent** 
https://github.com/alexsasharegan/vue-breakpoint/blob/master/src/components/breakpoint/component.ts

data and methods section has a field with the same name "unsubscribe"

**Comment by alexsasharegan** [comment]
Will fix.

**Comment by alexsasharegan** [comment]
If you don't mind, have a go with the latest release to see if things are cleared up.

https://github.com/alexsasharegan/vue-breakpoint/releases/tag/v2.1.0

**Comment by dmpotapenko** [comment]
@alexsasharegan It works clearly!
Thank you so much!
